#pragma once

enum class Errors {
	FIGURE_SIDES_0,
	TRIANGLE_SIDES_3,
	TRIANGLE_ANGLES_180,
	RIGHT_TRIANGLE_ANGLE_90,
	ISOSCELES_TRIANGLE_SIDES_EQ,
	ISOSCELES_TRIANGLE_ANGLES_EQ,
	EQUILATERAL_TRIANGLE_SIDES_EQ,
	EQUILATERAL_TRIANGLE_ANGLES_EQ,
	EQUILATERAL_TRIANGLE_ANGLES_EQ_60,
	QUADRANGLE_SIDES_4,
	QUADRANGLE_SIDE_0,
	QUADRANGLE_ANGLES_360,
	PARALLELOGRAM_SIDES_PAIR_EQ,
	PARALLELOGRAM_ANGLE_PAIR_EQ,
	RECTANGLE_ANGLE_90,
	RHOMB_SIDES_EQ,
	SQUARE_ANGLES_90,
};